### ISSUE TITLE
Build error in Ubuntu 22.04

### ISSUE THREAD

**Issue by bluemild44** [mischief/efivim#5]
Hello, I want to use vim in EFI environment.

So, 

1. apt install build-essential nasm mtools gdisk
2. git clone --depth=1 --recursive https://github.com/mischief/efivim
3. cd efivim
4. make

All is done.

But, build error ouccured as belows...

```
gcc  -c -I ./brotli/c/include -I .. -I ../Include/Common -I ../Include/ -I ../Include/IndustryStandard -I ../Common/ -I .. -I . -I ../Include/X64/ -MD -fshort-wchar -fno-strict-aliasing -fwrapv -fno-delete-null-pointer-checks -Wall -Werror -Wno-deprecated-declarations -Wno-stringop-truncation -Wno-restrict -Wno-unused-result -nostdlib -g -O2  brotli/c/dec/decode.c -o brotli/c/dec/decode.o
brotli/c/dec/decode.c:2033:41: error: argument 2 of type ‘const uint8_t *’ {aka ‘const unsigned char *’} declared as a pointer [-Werror=vla-parameter]
 2033 |     size_t encoded_size, const uint8_t* encoded_buffer, size_t* decoded_size,
      |                          ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
In file included from brotli/c/dec/decode.c:7:
./brotli/c/include/brotli/decode.h:204:19: note: previously declared as a variable length array ‘const uint8_t[*decoded_size]’ {aka ‘const unsigned char[*decoded_size]’}
  204 |     const uint8_t encoded_buffer[BROTLI_ARRAY_PARAM(encoded_size)],
      |     ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
brotli/c/dec/decode.c:2034:14: error: argument 4 of type ‘uint8_t *’ {aka ‘unsigned char *’} declared as a pointer [-Werror=vla-parameter]
 2034 |     uint8_t* decoded_buffer) {
      |     ~~~~~~~~~^~~~~~~~~~~~~~
In file included from brotli/c/dec/decode.c:7:
./brotli/c/include/brotli/decode.h:206:13: note: previously declared as a variable length array ‘uint8_t[encoded_size]’ {aka ‘unsigned char[encoded_size]’}
  206 |     uint8_t decoded_buffer[BROTLI_ARRAY_PARAM(*decoded_size)]);
      |     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

How to fix these error ?

Thanks.

**Comment by mischief** [comment]
thanks for filing the issue. i've updated the edk2 submodule which resolved the compilation error on my debian host; it should solve the same error on your ubuntu 22. please update and try again.

**Comment by mischief** [comment]
@bluemild44 fyi i created automated release artifact of vim.efi. you can download that if you don't want to build.

**Comment by bluemild44** [comment]
> thanks for filing the issue. i've updated the edk2 submodule which resolved the compilation error on my debian host; it should solve the same error on your ubuntu 22. please update and try again.


Thanks a lot !

I made vim.efi binary on my Ubuntu 22.04 system.

**Comment by bluemild44** [comment]
> @bluemild44 fyi i created automated release artifact of vim.efi. you can download that if you don't want to build.

More thanks !

But I can't find that download link of vim.efi.

**Comment by mischief** [comment]
check releases page https://github.com/mischief/efivim/releases.

**Comment by bluemild44** [comment]
> check releases page https://github.com/mischief/efivim/releases.

Many thanks your effort !
